### PR TITLE
Elasticbeanstalk env tags

### PR DESCRIPTION
**Pull request by atward**
Upgrades elasticbeanstalk_env.py to tag environments upon creation. Requires upgrade to boto3.

### CODE REVIEW

**Comment by hsingh** [comment]
This is a great add but I'm reluctant to increase the minimum requirement to boto3. Can we make it so tags are ignored if boto3 is not available but everything else works if boto3 is not installed?

**Comment by atward** [comment]
I agree, that would be ideal. However the code to support both versions of boto would require an almost complete overhaul of the current structure.

In lieu of that `elasticbeanstalk_env.py` could be replaced with a stub that then sources `_elasticbeanstalk_env_boto(2|3).py`

With ansible migrating to boto3 this may be a suitable migration strategy for this module, but it does create code duplication and maintenance issues.

**Comment by sidewinder12s** [comment]
I'd argue that upping to boto3 is fine. Ansible module extras isn't even excepting modules that are not boto3 and development on boto has been discontinued.

**Comment by fvant** [comment]
I am planning to use this in production and am in favor of a path that enables inclusion as a proper Ansible module, so yes, in favor of the upgrade to boto3.
@atward  are you also planning to upgrade the other 2 modules to boto3 ?

**Comment by sidewinder12s** [comment]
@hsingh Would you be more inclined to accept PRs to boto3 if all 3 modules got updated to Boto3?

**Pull request merged**
